---
version: "3.8"

services:
  ca-provisioner:
    image: mgvazquez/ca-provider-api:${STEP_CA_VERSION:-0.15.15}
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "443:443"
    environment:
      CI_DEBUG_TRACE: "${CI_DEBUG_TRACE:-False}"
      CA_PROVIDER_LONG_NAME: "${CA_PROVIDER_LONG_NAME:-'Scabb Island'}"
      CA_PROVIDER_SHORT_NAME: "${CA_PROVIDER_SHORT_NAME:-scbbi}"
      CA_PROVIDER_URL: "${CA_PROVIDER_URL:-ca.scabb-island.com.ar}"
      CA_PROVIDER_MAIL: "${CA_PROVIDER_MAIL:-'acme@scabb-island.com.ar'}"
      ROOT_CA_PASS: "${ROOT_CA_PASS:-/certs/rootca.pass}"
      ROOT_CA_CERT: "${ROOT_CA_CERT:-/certs/rootca.crt}"
      ROOT_CA_KEY: "${ROOT_CA_KEY:-/certs/rootca.key}"
    volumes:
      - "./step-home:/home/step"
      - "${LOCA_CA_PATH:-./ca-files}:/certs"